services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CACHE_BUST: "2025-08-21-user-deletion-fix"
    container_name: virtual-audience-app-v2-2-1
    restart: unless-stopped
    ports:
      - "80:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/virtual_audience
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=virtual_audience
      - SESSION_SECRET=virtual-audience-production-secret-change-in-production
      # SRS Server Configuration - reads from .env file or uses defaults
      - SRS_HOST=${SRS_HOST:-cdn2.obedtv.live}
      - SRS_WHIP_PORT=${SRS_WHIP_PORT:-1990}
      - SRS_API_PORT=${SRS_API_PORT:-1985}
      - SRS_USE_HTTPS=${SRS_USE_HTTPS:-true}
      # Email Configuration - Required for user registration and password reset functionality
      - SENDGRID_API_KEY=${SENDGRID_API_KEY:-}
      - SENDGRID_FROM_EMAIL=${SENDGRID_FROM_EMAIL:-alerts@obedtv.com}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - virtual-audience-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --no-verbose --tries=1 --spider http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15-alpine
    container_name: virtual-audience-db-v2-2-1
    restart: unless-stopped
    environment:
      - POSTGRES_DB=virtual_audience
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - virtual-audience-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d virtual_audience"]
      interval: 10s
      timeout: 5s
      retries: 5



volumes:
  postgres_data:

networks:
  virtual-audience-network:
    driver: bridge