-- Virtual Audience Platform v2.5 Production Database Fix
-- This script fixes existing Docker production databases that are missing v2.5 schema
-- Includes: assigned_server columns for multi-server WHIP load balancing
-- Includes: consent system for TBN Adult Likeness Authorization and Release
-- Includes: rooms for multi-participant streaming

-- Create missing enum types if they don't exist
DO $$ BEGIN
    CREATE TYPE user_role AS ENUM ('admin', 'engineer', 'user');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE message_type AS ENUM ('individual', 'broadcast', 'system');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE consent_type AS ENUM ('camera_microphone', 'recording', 'broadcast', 'privacy_policy', 'arbitration_class_waiver');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Add arbitration_class_waiver to consent_type enum if upgrading from older version
DO $$
BEGIN
    ALTER TYPE consent_type ADD VALUE IF NOT EXISTS 'arbitration_class_waiver';
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create session table for authentication if missing
CREATE TABLE IF NOT EXISTS "session" (
        "sid" varchar PRIMARY KEY NOT NULL,
        "sess" jsonb NOT NULL,
        "expire" timestamp NOT NULL
);

-- Create chat system tables if missing
CREATE TABLE IF NOT EXISTS "chat_messages" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "session_id" text NOT NULL,
        "sender_id" integer REFERENCES "users"("id"),
        "sender_name" text NOT NULL,
        "recipient_id" integer REFERENCES "users"("id"),
        "message_type" message_type DEFAULT 'individual' NOT NULL,
        "content" text NOT NULL,
        "created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "chat_participants" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "session_id" text NOT NULL,
        "user_id" integer REFERENCES "users"("id"),
        "username" text NOT NULL,
        "role" user_role NOT NULL,
        "is_online" boolean DEFAULT true NOT NULL,
        "joined_at" timestamp DEFAULT now() NOT NULL,
        "last_seen_at" timestamp DEFAULT now() NOT NULL
);

-- Create session tokens table if missing
CREATE TABLE IF NOT EXISTS "session_tokens" (
        "id" text PRIMARY KEY NOT NULL,
        "link_id" text,
        "link_type" text,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "expires_at" timestamp NOT NULL,
        "created_by" integer REFERENCES "users"("id")
);

-- Create viewer links table if missing
CREATE TABLE IF NOT EXISTS "viewer_links" (
        "id" text PRIMARY KEY NOT NULL,
        "return_feed" text NOT NULL,
        "chat_enabled" boolean DEFAULT false NOT NULL,
        "url" text NOT NULL,
        "session_token" text UNIQUE,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "expires_at" timestamp,
        "created_by" integer REFERENCES "users"("id")
);

-- Create short viewer links table if missing
CREATE TABLE IF NOT EXISTS "short_viewer_links" (
        "id" text PRIMARY KEY NOT NULL,
        "return_feed" text NOT NULL,
        "chat_enabled" boolean DEFAULT false NOT NULL,
        "session_token" text UNIQUE,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "expires_at" timestamp,
        "created_by" integer REFERENCES "users"("id")
);

-- Create password reset tokens table if missing
CREATE TABLE IF NOT EXISTS "password_reset_tokens" (
        "id" text PRIMARY KEY NOT NULL,
        "user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "token" text NOT NULL UNIQUE,
        "expires_at" timestamp NOT NULL,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "used" boolean DEFAULT false NOT NULL
);

-- Create registration tokens table if missing
CREATE TABLE IF NOT EXISTS "registration_tokens" (
        "id" varchar PRIMARY KEY DEFAULT gen_random_uuid(),
        "email" text NOT NULL UNIQUE,
        "role" user_role DEFAULT 'user' NOT NULL,
        "token" text NOT NULL UNIQUE,
        "inviter_user_id" integer REFERENCES "users"("id"),
        "expires_at" timestamp NOT NULL,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "used" boolean DEFAULT false NOT NULL
);

-- Create rooms tables if missing
CREATE TABLE IF NOT EXISTS "rooms" (
        "id" varchar PRIMARY KEY DEFAULT gen_random_uuid(),
        "name" text NOT NULL,
        "description" text,
        "max_participants" integer DEFAULT 10,
        "chat_enabled" boolean DEFAULT true NOT NULL,
        "is_active" boolean DEFAULT true NOT NULL,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "updated_at" timestamp DEFAULT now() NOT NULL,
        "created_by" integer REFERENCES "users"("id")
);

CREATE TABLE IF NOT EXISTS "room_participants" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "room_id" varchar NOT NULL REFERENCES "rooms"("id") ON DELETE CASCADE,
        "user_id" integer REFERENCES "users"("id") ON DELETE CASCADE,
        "guest_name" text,
        "stream_name" text,
        "is_streaming" boolean DEFAULT false NOT NULL,
        "joined_at" timestamp DEFAULT now() NOT NULL,
        "last_seen_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "room_stream_assignments" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "room_id" varchar NOT NULL REFERENCES "rooms"("id") ON DELETE CASCADE,
        "stream_name" text NOT NULL,
        "assigned_user_id" integer REFERENCES "users"("id"),
        "assigned_guest_name" text,
        "position" integer DEFAULT 0,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "created_by" integer REFERENCES "users"("id")
);

-- Create consent records table if missing
CREATE TABLE IF NOT EXISTS "consent_records" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "session_id" text,
        "user_id" integer REFERENCES "users"("id"),
        "guest_identifier" text,
        "consent_type" consent_type NOT NULL,
        "consent_text" text NOT NULL,
        "granted" boolean DEFAULT false NOT NULL,
        "ip_address" text,
        "user_agent" text,
        "stream_name" text,
        "granted_at" timestamp DEFAULT now() NOT NULL,
        "revoked_at" timestamp
);

-- Add missing columns to existing tables
DO $$ BEGIN
    -- Add session_token to generated_links if missing
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='generated_links' AND column_name='session_token') THEN
        ALTER TABLE "generated_links" ADD COLUMN "session_token" text UNIQUE;
    END IF;
    
    -- Add assigned_server to generated_links if missing (multi-server load balancing)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='generated_links' AND column_name='assigned_server') THEN
        ALTER TABLE "generated_links" ADD COLUMN "assigned_server" text;
    END IF;
    
    -- Add session_token to short_links if missing
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='short_links' AND column_name='session_token') THEN
        ALTER TABLE "short_links" ADD COLUMN "session_token" text UNIQUE;
    END IF;
    
    -- Add assigned_server to short_links if missing (multi-server load balancing)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='short_links' AND column_name='assigned_server') THEN
        ALTER TABLE "short_links" ADD COLUMN "assigned_server" text;
    END IF;
    
    -- Add updated_at to users if missing
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='users' AND column_name='updated_at') THEN
        ALTER TABLE "users" ADD COLUMN "updated_at" timestamp DEFAULT now() NOT NULL;
    END IF;
END $$;

-- Create all required indexes
CREATE INDEX IF NOT EXISTS "IDX_session_expire" ON "session" ("expire");
CREATE INDEX IF NOT EXISTS "session_tokens_link_id_idx" ON "session_tokens" ("link_id");
CREATE INDEX IF NOT EXISTS "session_tokens_link_type_idx" ON "session_tokens" ("link_type");
CREATE INDEX IF NOT EXISTS "session_tokens_expires_at_idx" ON "session_tokens" ("expires_at");
CREATE INDEX IF NOT EXISTS "chat_messages_session_id_idx" ON "chat_messages" ("session_id");
CREATE INDEX IF NOT EXISTS "chat_messages_sender_id_idx" ON "chat_messages" ("sender_id");
CREATE INDEX IF NOT EXISTS "chat_messages_created_at_idx" ON "chat_messages" ("created_at");
CREATE INDEX IF NOT EXISTS "chat_participants_session_id_idx" ON "chat_participants" ("session_id");
CREATE INDEX IF NOT EXISTS "chat_participants_user_id_idx" ON "chat_participants" ("user_id");
CREATE INDEX IF NOT EXISTS "chat_participants_is_online_idx" ON "chat_participants" ("is_online");
CREATE INDEX IF NOT EXISTS "generated_links_expires_at_idx" ON "generated_links" ("expires_at");
CREATE INDEX IF NOT EXISTS "generated_links_created_by_idx" ON "generated_links" ("created_by");
CREATE INDEX IF NOT EXISTS "short_links_expires_at_idx" ON "short_links" ("expires_at");
CREATE INDEX IF NOT EXISTS "short_links_created_by_idx" ON "short_links" ("created_by");
CREATE INDEX IF NOT EXISTS "viewer_links_expires_at_idx" ON "viewer_links" ("expires_at");
CREATE INDEX IF NOT EXISTS "viewer_links_created_by_idx" ON "viewer_links" ("created_by");
CREATE INDEX IF NOT EXISTS "short_viewer_links_expires_at_idx" ON "short_viewer_links" ("expires_at");
CREATE INDEX IF NOT EXISTS "short_viewer_links_created_by_idx" ON "short_viewer_links" ("created_by");
CREATE INDEX IF NOT EXISTS "password_reset_tokens_user_id_idx" ON "password_reset_tokens" ("user_id");
CREATE INDEX IF NOT EXISTS "password_reset_tokens_token_idx" ON "password_reset_tokens" ("token");
CREATE INDEX IF NOT EXISTS "registration_tokens_email_idx" ON "registration_tokens" ("email");
CREATE INDEX IF NOT EXISTS "registration_tokens_token_idx" ON "registration_tokens" ("token");
CREATE INDEX IF NOT EXISTS "rooms_created_by_idx" ON "rooms" ("created_by");
CREATE INDEX IF NOT EXISTS "rooms_is_active_idx" ON "rooms" ("is_active");
CREATE INDEX IF NOT EXISTS "room_participants_room_id_idx" ON "room_participants" ("room_id");
CREATE INDEX IF NOT EXISTS "room_participants_user_id_idx" ON "room_participants" ("user_id");
CREATE INDEX IF NOT EXISTS "room_participants_is_streaming_idx" ON "room_participants" ("is_streaming");
CREATE INDEX IF NOT EXISTS "room_stream_assignments_room_id_idx" ON "room_stream_assignments" ("room_id");
CREATE INDEX IF NOT EXISTS "room_stream_assignments_stream_name_idx" ON "room_stream_assignments" ("stream_name");
CREATE INDEX IF NOT EXISTS "consent_records_user_id_idx" ON "consent_records" ("user_id");
CREATE INDEX IF NOT EXISTS "consent_records_guest_identifier_idx" ON "consent_records" ("guest_identifier");
CREATE INDEX IF NOT EXISTS "consent_records_stream_name_idx" ON "consent_records" ("stream_name");
CREATE INDEX IF NOT EXISTS "consent_records_consent_type_idx" ON "consent_records" ("consent_type");
CREATE INDEX IF NOT EXISTS "consent_records_granted_at_idx" ON "consent_records" ("granted_at");

-- Verify schema is complete
SELECT 
    'Production Database v2.5 Fix Complete' as status,
    COUNT(*) as total_tables
FROM information_schema.tables 
WHERE table_schema = 'public';

\echo 'Production database successfully updated to Virtual Audience Platform v2.5 schema'
\echo 'Features: rooms, consent system (TBN Adult Likeness Authorization), multi-server WHIP load balancing, US broadcast compliance'
