-- Virtual Audience Platform v2.7 — Production Database Upgrade Script
-- Safe to run on any existing version; every statement is idempotent.
-- Covers ALL schema changes from v1 through v2.7 in a single pass.
--
-- Changelog applied by this script:
--   v2.0  — session_tokens, viewer_links, short_viewer_links, chat, rooms, consent
--   v2.1  — password_reset_tokens, registration_tokens
--   v2.2  — assigned_server (WHIP multi-server load balancing)
--   v2.3  — arbitration_class_waiver consent enum value
--   v2.4  — productions table, production_id/guest_name/guest_email on links
--   v2.5  — invite_status/invited_at on generated_links
--   v2.6  — return_feeds table, whep_servers table, assigned_whep_server on all link tables
--   v2.7  — rooms.production_id, return_feeds.fallback_server_address/2, monitored_servers table

-- ============================================================
-- ENUMS (safe — skips if already exists)
-- ============================================================

DO $$ BEGIN
    CREATE TYPE user_role AS ENUM ('admin', 'engineer', 'user');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE message_type AS ENUM ('individual', 'broadcast', 'system');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE consent_type AS ENUM ('camera_microphone', 'recording', 'broadcast', 'privacy_policy', 'arbitration_class_waiver');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE production_status AS ENUM ('draft', 'active', 'ended');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE invite_status AS ENUM ('pending', 'sent', 'failed');
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- Add arbitration_class_waiver if upgrading from older consent_type enum (v2.3 patch)
DO $$
BEGIN
    ALTER TYPE consent_type ADD VALUE IF NOT EXISTS 'arbitration_class_waiver';
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- ============================================================
-- CORE TABLES (CREATE IF NOT EXISTS)
-- ============================================================

CREATE TABLE IF NOT EXISTS "session" (
        "sid" varchar PRIMARY KEY NOT NULL,
        "sess" jsonb NOT NULL,
        "expire" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "session_tokens" (
        "id" text PRIMARY KEY NOT NULL,
        "link_id" text,
        "link_type" text,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "expires_at" timestamp NOT NULL,
        "created_by" integer REFERENCES "users"("id")
);

-- ============================================================
-- CHAT TABLES
-- ============================================================

CREATE TABLE IF NOT EXISTS "chat_messages" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "session_id" text NOT NULL,
        "sender_id" integer REFERENCES "users"("id"),
        "sender_name" text NOT NULL,
        "recipient_id" integer REFERENCES "users"("id"),
        "message_type" message_type DEFAULT 'individual' NOT NULL,
        "content" text NOT NULL,
        "created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "chat_participants" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "session_id" text NOT NULL,
        "user_id" integer REFERENCES "users"("id"),
        "username" text NOT NULL,
        "role" user_role NOT NULL,
        "is_online" boolean DEFAULT true NOT NULL,
        "joined_at" timestamp DEFAULT now() NOT NULL,
        "last_seen_at" timestamp DEFAULT now() NOT NULL
);

-- ============================================================
-- VIEWER / SHORT-VIEWER LINK TABLES
-- ============================================================

CREATE TABLE IF NOT EXISTS "viewer_links" (
        "id" text PRIMARY KEY NOT NULL,
        "return_feed" text NOT NULL,
        "chat_enabled" boolean DEFAULT false NOT NULL,
        "url" text NOT NULL,
        "session_token" text UNIQUE,
        "assigned_whep_server" text,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "expires_at" timestamp,
        "created_by" integer REFERENCES "users"("id")
);

CREATE TABLE IF NOT EXISTS "short_viewer_links" (
        "id" text PRIMARY KEY NOT NULL,
        "return_feed" text NOT NULL,
        "chat_enabled" boolean DEFAULT false NOT NULL,
        "session_token" text UNIQUE,
        "assigned_whep_server" text,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "expires_at" timestamp,
        "created_by" integer REFERENCES "users"("id")
);

-- ============================================================
-- AUTH TOKEN TABLES
-- ============================================================

CREATE TABLE IF NOT EXISTS "password_reset_tokens" (
        "id" text PRIMARY KEY NOT NULL,
        "user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "token" text NOT NULL UNIQUE,
        "expires_at" timestamp NOT NULL,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "used" boolean DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS "registration_tokens" (
        "id" varchar PRIMARY KEY DEFAULT gen_random_uuid(),
        "email" text NOT NULL UNIQUE,
        "role" user_role DEFAULT 'user' NOT NULL,
        "token" text NOT NULL UNIQUE,
        "inviter_user_id" integer REFERENCES "users"("id"),
        "expires_at" timestamp NOT NULL,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "used" boolean DEFAULT false NOT NULL
);

-- ============================================================
-- ROOM TABLES
-- ============================================================

CREATE TABLE IF NOT EXISTS "rooms" (
        "id" varchar PRIMARY KEY DEFAULT gen_random_uuid(),
        "name" text NOT NULL,
        "description" text,
        "max_participants" integer DEFAULT 10,
        "chat_enabled" boolean DEFAULT true NOT NULL,
        "is_active" boolean DEFAULT true NOT NULL,
        "production_id" varchar REFERENCES "productions"("id") ON DELETE SET NULL,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "updated_at" timestamp DEFAULT now() NOT NULL,
        "created_by" integer REFERENCES "users"("id")
);

CREATE TABLE IF NOT EXISTS "room_participants" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "room_id" varchar NOT NULL REFERENCES "rooms"("id") ON DELETE CASCADE,
        "user_id" integer REFERENCES "users"("id") ON DELETE CASCADE,
        "guest_name" text,
        "stream_name" text,
        "is_streaming" boolean DEFAULT false NOT NULL,
        "joined_at" timestamp DEFAULT now() NOT NULL,
        "last_seen_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "room_stream_assignments" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "room_id" varchar NOT NULL REFERENCES "rooms"("id") ON DELETE CASCADE,
        "stream_name" text NOT NULL,
        "assigned_user_id" integer REFERENCES "users"("id"),
        "assigned_guest_name" text,
        "position" integer DEFAULT 0,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "created_by" integer REFERENCES "users"("id")
);

-- ============================================================
-- CONSENT TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS "consent_records" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "session_id" text,
        "user_id" integer REFERENCES "users"("id"),
        "guest_identifier" text,
        "consent_type" consent_type NOT NULL,
        "consent_text" text NOT NULL,
        "granted" boolean DEFAULT false NOT NULL,
        "ip_address" text,
        "user_agent" text,
        "stream_name" text,
        "granted_at" timestamp DEFAULT now() NOT NULL,
        "revoked_at" timestamp
);

-- ============================================================
-- PRODUCTIONS TABLE (v2.4)
-- ============================================================

CREATE TABLE IF NOT EXISTS "productions" (
        "id" varchar PRIMARY KEY DEFAULT gen_random_uuid(),
        "name" text NOT NULL,
        "description" text,
        "scheduled_at" timestamp,
        "status" production_status NOT NULL DEFAULT 'draft',
        "max_live_participants" integer NOT NULL DEFAULT 128,
        "return_feed" text NOT NULL DEFAULT '',
        "assigned_server" text,
        "created_at" timestamp NOT NULL DEFAULT now(),
        "updated_at" timestamp NOT NULL DEFAULT now(),
        "created_by" integer REFERENCES "users"("id")
);

-- ============================================================
-- RETURN FEEDS TABLE (v2.6)
-- ============================================================

CREATE TABLE IF NOT EXISTS "return_feeds" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "label" text NOT NULL,
        "stream_name" text NOT NULL,
        "server_address" text,
        "fallback_server_address" text,
        "fallback_server_address2" text,
        "sort_order" integer NOT NULL DEFAULT 0,
        "created_at" timestamp NOT NULL DEFAULT now()
);

-- ============================================================
-- WHEP SERVER POOL TABLE (v2.6)
-- ============================================================

CREATE TABLE IF NOT EXISTS "whep_servers" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "label" text NOT NULL,
        "address" text NOT NULL,
        "is_active" boolean NOT NULL DEFAULT true,
        "sort_order" integer NOT NULL DEFAULT 0,
        "created_at" timestamp NOT NULL DEFAULT now()
);

-- ============================================================
-- ADD MISSING COLUMNS TO EXISTING TABLES (all idempotent)
-- ============================================================

DO $$ BEGIN

    -- users: updated_at (v2.0)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='users' AND column_name='updated_at') THEN
        ALTER TABLE "users" ADD COLUMN "updated_at" timestamp DEFAULT now() NOT NULL;
    END IF;

    -- generated_links: session_token (v2.0)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='generated_links' AND column_name='session_token') THEN
        ALTER TABLE "generated_links" ADD COLUMN "session_token" text UNIQUE;
    END IF;

    -- generated_links: assigned_server / WHIP load balancing (v2.2)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='generated_links' AND column_name='assigned_server') THEN
        ALTER TABLE "generated_links" ADD COLUMN "assigned_server" text;
    END IF;

    -- generated_links: production linking (v2.4)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='generated_links' AND column_name='production_id') THEN
        ALTER TABLE "generated_links" ADD COLUMN "production_id" varchar REFERENCES "productions"("id") ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='generated_links' AND column_name='guest_name') THEN
        ALTER TABLE "generated_links" ADD COLUMN "guest_name" text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='generated_links' AND column_name='guest_email') THEN
        ALTER TABLE "generated_links" ADD COLUMN "guest_email" text;
    END IF;

    -- generated_links: invite campaign status (v2.5)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='generated_links' AND column_name='invite_status') THEN
        ALTER TABLE "generated_links" ADD COLUMN "invite_status" invite_status;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='generated_links' AND column_name='invited_at') THEN
        ALTER TABLE "generated_links" ADD COLUMN "invited_at" timestamp;
    END IF;

    -- generated_links: dedicated WHEP server (v2.6)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='generated_links' AND column_name='assigned_whep_server') THEN
        ALTER TABLE "generated_links" ADD COLUMN "assigned_whep_server" text;
    END IF;

    -- short_links: session_token (v2.0)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='short_links' AND column_name='session_token') THEN
        ALTER TABLE "short_links" ADD COLUMN "session_token" text UNIQUE;
    END IF;

    -- short_links: assigned_server (v2.2)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='short_links' AND column_name='assigned_server') THEN
        ALTER TABLE "short_links" ADD COLUMN "assigned_server" text;
    END IF;

    -- short_links: production linking (v2.4)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='short_links' AND column_name='production_id') THEN
        ALTER TABLE "short_links" ADD COLUMN "production_id" varchar REFERENCES "productions"("id") ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='short_links' AND column_name='guest_name') THEN
        ALTER TABLE "short_links" ADD COLUMN "guest_name" text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='short_links' AND column_name='guest_email') THEN
        ALTER TABLE "short_links" ADD COLUMN "guest_email" text;
    END IF;

    -- short_links: dedicated WHEP server (v2.6)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='short_links' AND column_name='assigned_whep_server') THEN
        ALTER TABLE "short_links" ADD COLUMN "assigned_whep_server" text;
    END IF;

    -- viewer_links: session_token (v2.0)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='viewer_links' AND column_name='session_token') THEN
        ALTER TABLE "viewer_links" ADD COLUMN "session_token" text UNIQUE;
    END IF;

    -- viewer_links: dedicated WHEP server (v2.6)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='viewer_links' AND column_name='assigned_whep_server') THEN
        ALTER TABLE "viewer_links" ADD COLUMN "assigned_whep_server" text;
    END IF;

    -- short_viewer_links: session_token, expires_at, created_by (v2.0)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='short_viewer_links' AND column_name='session_token') THEN
        ALTER TABLE "short_viewer_links" ADD COLUMN "session_token" text UNIQUE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='short_viewer_links' AND column_name='expires_at') THEN
        ALTER TABLE "short_viewer_links" ADD COLUMN "expires_at" timestamp;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='short_viewer_links' AND column_name='created_by') THEN
        ALTER TABLE "short_viewer_links" ADD COLUMN "created_by" integer REFERENCES "users"("id");
    END IF;

    -- short_viewer_links: dedicated WHEP server (v2.6)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='short_viewer_links' AND column_name='assigned_whep_server') THEN
        ALTER TABLE "short_viewer_links" ADD COLUMN "assigned_whep_server" text;
    END IF;

    -- rooms: production assignment (v2.7)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='rooms' AND column_name='production_id') THEN
        ALTER TABLE "rooms" ADD COLUMN "production_id" varchar REFERENCES "productions"("id") ON DELETE SET NULL;
    END IF;

    -- return_feeds: fallback server address (v2.7)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='return_feeds' AND column_name='fallback_server_address') THEN
        ALTER TABLE "return_feeds" ADD COLUMN "fallback_server_address" text;
    END IF;

    -- return_feeds: 3rd fallback server address for round-robin rotation (v2.7)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='return_feeds' AND column_name='fallback_server_address2') THEN
        ALTER TABLE "return_feeds" ADD COLUMN "fallback_server_address2" text;
    END IF;

END $$;

-- ============================================================
-- MONITORED SERVERS TABLE (v2.7 — dashboard server health monitors)
-- ============================================================

CREATE TABLE IF NOT EXISTS "monitored_servers" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "name" text NOT NULL,
        "address" text NOT NULL,
        "api_port" integer NOT NULL DEFAULT 1985,
        "use_https" boolean NOT NULL DEFAULT false,
        "api_secret" text,
        "created_at" timestamp NOT NULL DEFAULT now(),
        "created_by" integer REFERENCES "users"("id")
);

-- ============================================================
-- INDEXES (all idempotent via IF NOT EXISTS)
-- ============================================================

CREATE INDEX IF NOT EXISTS "IDX_session_expire"                    ON "session"               ("expire");
CREATE INDEX IF NOT EXISTS "session_tokens_link_id_idx"            ON "session_tokens"         ("link_id");
CREATE INDEX IF NOT EXISTS "session_tokens_link_type_idx"          ON "session_tokens"         ("link_type");
CREATE INDEX IF NOT EXISTS "session_tokens_expires_at_idx"         ON "session_tokens"         ("expires_at");
CREATE INDEX IF NOT EXISTS "chat_messages_session_id_idx"          ON "chat_messages"          ("session_id");
CREATE INDEX IF NOT EXISTS "chat_messages_sender_id_idx"           ON "chat_messages"          ("sender_id");
CREATE INDEX IF NOT EXISTS "chat_messages_created_at_idx"          ON "chat_messages"          ("created_at");
CREATE INDEX IF NOT EXISTS "chat_participants_session_id_idx"      ON "chat_participants"       ("session_id");
CREATE INDEX IF NOT EXISTS "chat_participants_user_id_idx"         ON "chat_participants"       ("user_id");
CREATE INDEX IF NOT EXISTS "chat_participants_username_idx"        ON "chat_participants"       ("username");
CREATE INDEX IF NOT EXISTS "chat_participants_is_online_idx"       ON "chat_participants"       ("is_online");
CREATE INDEX IF NOT EXISTS "generated_links_expires_at_idx"        ON "generated_links"        ("expires_at");
CREATE INDEX IF NOT EXISTS "generated_links_created_by_idx"        ON "generated_links"        ("created_by");
CREATE INDEX IF NOT EXISTS "generated_links_production_id_idx"     ON "generated_links"        ("production_id");
CREATE INDEX IF NOT EXISTS "short_links_expires_at_idx"            ON "short_links"            ("expires_at");
CREATE INDEX IF NOT EXISTS "short_links_created_by_idx"            ON "short_links"            ("created_by");
CREATE INDEX IF NOT EXISTS "short_links_production_id_idx"         ON "short_links"            ("production_id");
CREATE INDEX IF NOT EXISTS "viewer_links_expires_at_idx"           ON "viewer_links"           ("expires_at");
CREATE INDEX IF NOT EXISTS "viewer_links_created_by_idx"           ON "viewer_links"           ("created_by");
CREATE INDEX IF NOT EXISTS "short_viewer_links_expires_at_idx"     ON "short_viewer_links"     ("expires_at");
CREATE INDEX IF NOT EXISTS "short_viewer_links_created_by_idx"     ON "short_viewer_links"     ("created_by");
CREATE INDEX IF NOT EXISTS "password_reset_tokens_user_id_idx"     ON "password_reset_tokens"  ("user_id");
CREATE INDEX IF NOT EXISTS "password_reset_tokens_token_idx"       ON "password_reset_tokens"  ("token");
CREATE INDEX IF NOT EXISTS "registration_tokens_email_idx"         ON "registration_tokens"    ("email");
CREATE INDEX IF NOT EXISTS "registration_tokens_token_idx"         ON "registration_tokens"    ("token");
CREATE INDEX IF NOT EXISTS "consent_records_user_id_idx"           ON "consent_records"        ("user_id");
CREATE INDEX IF NOT EXISTS "consent_records_guest_identifier_idx"  ON "consent_records"        ("guest_identifier");
CREATE INDEX IF NOT EXISTS "consent_records_stream_name_idx"       ON "consent_records"        ("stream_name");
CREATE INDEX IF NOT EXISTS "consent_records_consent_type_idx"      ON "consent_records"        ("consent_type");
CREATE INDEX IF NOT EXISTS "consent_records_granted_at_idx"        ON "consent_records"        ("granted_at");
CREATE INDEX IF NOT EXISTS "rooms_created_by_idx"                  ON "rooms"                  ("created_by");
CREATE INDEX IF NOT EXISTS "rooms_is_active_idx"                   ON "rooms"                  ("is_active");
CREATE INDEX IF NOT EXISTS "rooms_production_id_idx"               ON "rooms"                  ("production_id");
CREATE INDEX IF NOT EXISTS "room_participants_room_id_idx"         ON "room_participants"       ("room_id");
CREATE INDEX IF NOT EXISTS "room_participants_user_id_idx"         ON "room_participants"       ("user_id");
CREATE INDEX IF NOT EXISTS "room_participants_is_streaming_idx"    ON "room_participants"       ("is_streaming");
CREATE INDEX IF NOT EXISTS "room_stream_assignments_room_id_idx"   ON "room_stream_assignments" ("room_id");
CREATE INDEX IF NOT EXISTS "room_stream_assignments_stream_name_idx" ON "room_stream_assignments" ("stream_name");
CREATE INDEX IF NOT EXISTS "productions_status_idx"                ON "productions"            ("status");
CREATE INDEX IF NOT EXISTS "productions_created_by_idx"            ON "productions"            ("created_by");
CREATE INDEX IF NOT EXISTS "return_feeds_sort_order_idx"           ON "return_feeds"           ("sort_order");
CREATE INDEX IF NOT EXISTS "whep_servers_is_active_idx"            ON "whep_servers"           ("is_active");
CREATE INDEX IF NOT EXISTS "whep_servers_sort_order_idx"           ON "whep_servers"           ("sort_order");
CREATE INDEX IF NOT EXISTS "monitored_servers_created_by_idx"      ON "monitored_servers"      ("created_by");

-- ============================================================
-- NO SEED DATA HERE — this script runs on every container start.
-- Default return feeds (Socal 1-6, Plex 1-8) are seeded exactly once:
--   • Fresh installs  → init.sql  (runs via docker-entrypoint-initdb.d on new volumes)
--   • Legacy upgrades → migrations/0003_return_feeds_whep_servers.sql (run manually once)
-- Any return feeds you add or remove in the Admin UI are safe across rebuilds.
-- ============================================================

-- ============================================================
-- VERIFICATION
-- ============================================================

SELECT
    'v2.6 Upgrade Verification' AS status,
    COUNT(*) AS public_tables
FROM information_schema.tables
WHERE table_schema = 'public';

SELECT table_name AS verified_table
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN (
        'session', 'users',
        'productions',
        'generated_links', 'short_links', 'viewer_links', 'short_viewer_links',
        'session_tokens',
        'chat_messages', 'chat_participants',
        'rooms', 'room_participants', 'room_stream_assignments',
        'password_reset_tokens', 'registration_tokens',
        'consent_records',
        'return_feeds', 'whep_servers'
  )
ORDER BY table_name;

\echo 'Virtual Audience Platform v2.7 production database upgrade completed successfully'
\echo 'All schema changes from v1 through v2.7 have been applied.'
