-- Virtual Audience Platform v2.4 with Authentication, Session Tokens, and Multi-Server Load Balancing
-- Clean initialization for Docker deployment
-- Includes: assigned_server columns for WHIP server load balancing

-- Create database if not exists
SELECT 'CREATE DATABASE virtual_audience'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'virtual_audience');

-- Connect to the database
\c virtual_audience;

-- Clean slate: Drop existing schema for fresh deployment
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

-- Grant all privileges to postgres user for Drizzle operations
GRANT ALL PRIVILEGES ON DATABASE virtual_audience TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA public TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres;

-- Allow future objects
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;

-- Create full database schema for Virtual Audience Platform v2.0

-- Create enums first (safe creation)
DO $$ BEGIN
    CREATE TYPE user_role AS ENUM ('admin', 'engineer', 'user');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE message_type AS ENUM ('individual', 'broadcast', 'system');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Session storage table for authentication sessions
CREATE TABLE IF NOT EXISTS "session" (
        "sid" varchar PRIMARY KEY NOT NULL,
        "sess" jsonb NOT NULL,
        "expire" timestamp NOT NULL
);

-- Users table with authentication support
CREATE TABLE IF NOT EXISTS "users" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "username" varchar(50) NOT NULL,
        "password" text NOT NULL,
        "email" varchar(100),
        "role" user_role DEFAULT 'user' NOT NULL,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "updated_at" timestamp DEFAULT now() NOT NULL,
        CONSTRAINT "users_username_unique" UNIQUE("username")
);

-- Generated links table for streaming session management (main table)
CREATE TABLE IF NOT EXISTS "generated_links" (
        "id" text PRIMARY KEY NOT NULL,
        "stream_name" text NOT NULL,
        "return_feed" text NOT NULL,
        "chat_enabled" boolean DEFAULT false NOT NULL,
        "url" text NOT NULL,
        "session_token" text UNIQUE,
        "assigned_server" text,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "expires_at" timestamp,
        "created_by" integer REFERENCES "users"("id")
);

-- Short links table for URL shortening
CREATE TABLE IF NOT EXISTS "short_links" (
        "id" text PRIMARY KEY NOT NULL,
        "stream_name" text NOT NULL,
        "return_feed" text NOT NULL,
        "chat_enabled" boolean DEFAULT false NOT NULL,
        "session_token" text UNIQUE,
        "assigned_server" text,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "expires_at" timestamp,
        "created_by" integer REFERENCES "users"("id")
);

-- Viewer links table for studio monitoring
CREATE TABLE IF NOT EXISTS "viewer_links" (
        "id" text PRIMARY KEY NOT NULL,
        "return_feed" text NOT NULL,
        "chat_enabled" boolean DEFAULT false NOT NULL,
        "url" text NOT NULL,
        "session_token" text UNIQUE,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "expires_at" timestamp,
        "created_by" integer REFERENCES "users"("id")
);

-- Short viewer links table for URL shortening
CREATE TABLE IF NOT EXISTS "short_viewer_links" (
        "id" text PRIMARY KEY NOT NULL,
        "return_feed" text NOT NULL,
        "chat_enabled" boolean DEFAULT false NOT NULL,
        "session_token" text UNIQUE,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "expires_at" timestamp,
        "created_by" integer REFERENCES "users"("id")
);

-- Session tokens table for reusable link security
CREATE TABLE IF NOT EXISTS "session_tokens" (
        "id" text PRIMARY KEY NOT NULL,
        "link_id" text,
        "link_type" text,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "expires_at" timestamp NOT NULL,
        "created_by" integer REFERENCES "users"("id")
);

-- Chat system tables
CREATE TABLE IF NOT EXISTS "chat_messages" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "session_id" text NOT NULL,
        "sender_id" integer REFERENCES "users"("id"),
        "sender_name" text NOT NULL,
        "recipient_id" integer REFERENCES "users"("id"),
        "message_type" message_type DEFAULT 'individual' NOT NULL,
        "content" text NOT NULL,
        "created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "chat_participants" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "session_id" text NOT NULL,
        "user_id" integer REFERENCES "users"("id"),
        "username" text NOT NULL,
        "role" user_role NOT NULL,
        "is_online" boolean DEFAULT true NOT NULL,
        "joined_at" timestamp DEFAULT now() NOT NULL,
        "last_seen_at" timestamp DEFAULT now() NOT NULL
);

-- Room system tables for multi-participant streaming
CREATE TABLE IF NOT EXISTS "rooms" (
        "id" varchar PRIMARY KEY DEFAULT gen_random_uuid(),
        "name" text NOT NULL,
        "description" text,
        "max_participants" integer DEFAULT 10,
        "chat_enabled" boolean DEFAULT true NOT NULL,
        "is_active" boolean DEFAULT true NOT NULL,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "updated_at" timestamp DEFAULT now() NOT NULL,
        "created_by" integer REFERENCES "users"("id")
);

CREATE TABLE IF NOT EXISTS "room_participants" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "room_id" varchar NOT NULL REFERENCES "rooms"("id") ON DELETE CASCADE,
        "user_id" integer REFERENCES "users"("id") ON DELETE CASCADE,
        "guest_name" text,
        "stream_name" text,
        "is_streaming" boolean DEFAULT false NOT NULL,
        "joined_at" timestamp DEFAULT now() NOT NULL,
        "last_seen_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "room_stream_assignments" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "room_id" varchar NOT NULL REFERENCES "rooms"("id") ON DELETE CASCADE,
        "stream_name" text NOT NULL,
        "assigned_user_id" integer REFERENCES "users"("id"),
        "assigned_guest_name" text,
        "position" integer DEFAULT 0,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "created_by" integer REFERENCES "users"("id")
);

-- Password reset tokens table
CREATE TABLE IF NOT EXISTS "password_reset_tokens" (
        "id" text PRIMARY KEY NOT NULL,
        "user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
        "token" text NOT NULL UNIQUE,
        "expires_at" timestamp NOT NULL,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "used" boolean DEFAULT false NOT NULL
);

-- Registration tokens table for user invites
CREATE TABLE IF NOT EXISTS "registration_tokens" (
        "id" varchar PRIMARY KEY DEFAULT gen_random_uuid(),
        "email" text NOT NULL UNIQUE,
        "role" user_role DEFAULT 'user' NOT NULL,
        "token" text NOT NULL UNIQUE,
        "inviter_user_id" integer REFERENCES "users"("id"),
        "expires_at" timestamp NOT NULL,
        "created_at" timestamp DEFAULT now() NOT NULL,
        "used" boolean DEFAULT false NOT NULL
);

-- Consent system for US broadcast compliance
DO $$ BEGIN
    CREATE TYPE consent_type AS ENUM ('camera_microphone', 'recording', 'broadcast', 'privacy_policy');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS "consent_records" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "session_id" text,
        "user_id" integer REFERENCES "users"("id"),
        "guest_identifier" text,
        "consent_type" consent_type NOT NULL,
        "consent_text" text NOT NULL,
        "granted" boolean DEFAULT false NOT NULL,
        "ip_address" text,
        "user_agent" text,
        "stream_name" text,
        "granted_at" timestamp DEFAULT now() NOT NULL,
        "revoked_at" timestamp
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS "IDX_session_expire" ON "session" ("expire");
CREATE INDEX IF NOT EXISTS "session_tokens_link_id_idx" ON "session_tokens" ("link_id");
CREATE INDEX IF NOT EXISTS "session_tokens_link_type_idx" ON "session_tokens" ("link_type");
CREATE INDEX IF NOT EXISTS "session_tokens_expires_at_idx" ON "session_tokens" ("expires_at");

-- Chat system indexes
CREATE INDEX IF NOT EXISTS "chat_messages_session_id_idx" ON "chat_messages" ("session_id");
CREATE INDEX IF NOT EXISTS "chat_messages_sender_id_idx" ON "chat_messages" ("sender_id");
CREATE INDEX IF NOT EXISTS "chat_messages_created_at_idx" ON "chat_messages" ("created_at");
CREATE INDEX IF NOT EXISTS "chat_participants_session_id_idx" ON "chat_participants" ("session_id");
CREATE INDEX IF NOT EXISTS "chat_participants_user_id_idx" ON "chat_participants" ("user_id");
CREATE INDEX IF NOT EXISTS "chat_participants_is_online_idx" ON "chat_participants" ("is_online");

-- Link table indexes for performance
CREATE INDEX IF NOT EXISTS "generated_links_expires_at_idx" ON "generated_links" ("expires_at");
CREATE INDEX IF NOT EXISTS "generated_links_created_by_idx" ON "generated_links" ("created_by");
CREATE INDEX IF NOT EXISTS "short_links_expires_at_idx" ON "short_links" ("expires_at");
CREATE INDEX IF NOT EXISTS "short_links_created_by_idx" ON "short_links" ("created_by");
CREATE INDEX IF NOT EXISTS "viewer_links_expires_at_idx" ON "viewer_links" ("expires_at");
CREATE INDEX IF NOT EXISTS "viewer_links_created_by_idx" ON "viewer_links" ("created_by");
CREATE INDEX IF NOT EXISTS "short_viewer_links_expires_at_idx" ON "short_viewer_links" ("expires_at");
CREATE INDEX IF NOT EXISTS "short_viewer_links_created_by_idx" ON "short_viewer_links" ("created_by");

-- Password reset and registration token indexes
CREATE INDEX IF NOT EXISTS "password_reset_tokens_user_id_idx" ON "password_reset_tokens" ("user_id");
CREATE INDEX IF NOT EXISTS "password_reset_tokens_token_idx" ON "password_reset_tokens" ("token");
CREATE INDEX IF NOT EXISTS "registration_tokens_email_idx" ON "registration_tokens" ("email");
CREATE INDEX IF NOT EXISTS "registration_tokens_token_idx" ON "registration_tokens" ("token");

-- Consent system indexes
CREATE INDEX IF NOT EXISTS "consent_records_user_id_idx" ON "consent_records" ("user_id");
CREATE INDEX IF NOT EXISTS "consent_records_guest_identifier_idx" ON "consent_records" ("guest_identifier");
CREATE INDEX IF NOT EXISTS "consent_records_stream_name_idx" ON "consent_records" ("stream_name");
CREATE INDEX IF NOT EXISTS "consent_records_consent_type_idx" ON "consent_records" ("consent_type");
CREATE INDEX IF NOT EXISTS "consent_records_granted_at_idx" ON "consent_records" ("granted_at");

-- Room system indexes
CREATE INDEX IF NOT EXISTS "rooms_created_by_idx" ON "rooms" ("created_by");
CREATE INDEX IF NOT EXISTS "rooms_is_active_idx" ON "rooms" ("is_active");
CREATE INDEX IF NOT EXISTS "room_participants_room_id_idx" ON "room_participants" ("room_id");
CREATE INDEX IF NOT EXISTS "room_participants_user_id_idx" ON "room_participants" ("user_id");
CREATE INDEX IF NOT EXISTS "room_participants_is_streaming_idx" ON "room_participants" ("is_streaming");
CREATE INDEX IF NOT EXISTS "room_stream_assignments_room_id_idx" ON "room_stream_assignments" ("room_id");
CREATE INDEX IF NOT EXISTS "room_stream_assignments_stream_name_idx" ON "room_stream_assignments" ("stream_name");

-- Create default admin user (password: password - MUST be changed in production)
INSERT INTO "users" ("username", "email", "password", "role")
VALUES ('admin', 'admin@stagelinq.com', 'd50f2345138be5a9d2e393d0d35bc3e79b6e0de2ef0fcbb2e6420cbbc637db4e25cfbb47c1e3079f805a84dc9379c559747529728eb0d1c35b92b1b07fb0d68c.2dc356427cd6587959802211b6e98ace', 'admin')
ON CONFLICT ("username") DO NOTHING;

-- Notify successful initialization
\echo 'Virtual Audience Platform v2.4 database schema initialized successfully with rooms, consent system, multi-server load balancing, and US broadcast compliance support';