-- Virtual Audience Platform v2.6 Migration
-- Applies on top of 0002_invite_status.sql for existing production databases
-- Adds: return_feeds table, whep_servers table, assigned_whep_server column on all link tables

-- ============================================================
-- NEW ENUMS (safe — no-op if already exists)
-- ============================================================

-- production_status and invite_status may already exist if 0001/0002 ran;
-- these blocks are safe to re-run.
DO $$ BEGIN
    CREATE TYPE production_status AS ENUM ('draft', 'active', 'ended');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE invite_status AS ENUM ('pending', 'sent', 'failed');
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- ============================================================
-- PRODUCTIONS TABLE (if somehow missing — 0001 should have added it)
-- ============================================================

CREATE TABLE IF NOT EXISTS "productions" (
        "id" varchar PRIMARY KEY DEFAULT gen_random_uuid(),
        "name" text NOT NULL,
        "description" text,
        "scheduled_at" timestamp,
        "status" production_status NOT NULL DEFAULT 'draft',
        "max_live_participants" integer NOT NULL DEFAULT 128,
        "return_feed" text NOT NULL DEFAULT '',
        "assigned_server" text,
        "created_at" timestamp NOT NULL DEFAULT now(),
        "updated_at" timestamp NOT NULL DEFAULT now(),
        "created_by" integer REFERENCES "users"("id")
);

-- ============================================================
-- RETURN FEEDS TABLE (new in v2.6)
-- ============================================================

CREATE TABLE IF NOT EXISTS "return_feeds" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "label" text NOT NULL,
        "stream_name" text NOT NULL,
        "server_address" text,
        "sort_order" integer NOT NULL DEFAULT 0,
        "created_at" timestamp NOT NULL DEFAULT now()
);

-- ============================================================
-- WHEP SERVER POOL TABLE (new in v2.6)
-- Dedicated servers for return feed delivery to guests,
-- assigned round-robin at link generation time.
-- ============================================================

CREATE TABLE IF NOT EXISTS "whep_servers" (
        "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "label" text NOT NULL,
        "address" text NOT NULL,
        "is_active" boolean NOT NULL DEFAULT true,
        "sort_order" integer NOT NULL DEFAULT 0,
        "created_at" timestamp NOT NULL DEFAULT now()
);

-- ============================================================
-- NEW COLUMNS ON EXISTING TABLES
-- All ALTER TABLE statements use IF NOT EXISTS to be safe.
-- ============================================================

-- generated_links: assigned_whep_server (v2.6)
ALTER TABLE "generated_links"
  ADD COLUMN IF NOT EXISTS "assigned_whep_server" text;

-- generated_links: productions FK + guest info (should exist from 0001, safe to repeat)
ALTER TABLE "generated_links"
  ADD COLUMN IF NOT EXISTS "production_id" varchar REFERENCES "productions"("id") ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS "guest_name"    text,
  ADD COLUMN IF NOT EXISTS "guest_email"   text;

-- generated_links: invite status (should exist from 0002, safe to repeat)
ALTER TABLE "generated_links"
  ADD COLUMN IF NOT EXISTS "invite_status" invite_status,
  ADD COLUMN IF NOT EXISTS "invited_at"    timestamp;

-- short_links: assigned_whep_server (v2.6)
ALTER TABLE "short_links"
  ADD COLUMN IF NOT EXISTS "assigned_whep_server" text;

-- short_links: productions FK + guest info (should exist from 0001, safe to repeat)
ALTER TABLE "short_links"
  ADD COLUMN IF NOT EXISTS "production_id" varchar REFERENCES "productions"("id") ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS "guest_name"    text,
  ADD COLUMN IF NOT EXISTS "guest_email"   text;

-- viewer_links: assigned_whep_server (v2.6)
ALTER TABLE "viewer_links"
  ADD COLUMN IF NOT EXISTS "assigned_whep_server" text;

-- short_viewer_links: assigned_whep_server (v2.6)
ALTER TABLE "short_viewer_links"
  ADD COLUMN IF NOT EXISTS "assigned_whep_server" text;

-- ============================================================
-- NEW INDEXES
-- ============================================================

CREATE INDEX IF NOT EXISTS "generated_links_production_id_idx" ON "generated_links" ("production_id");
CREATE INDEX IF NOT EXISTS "short_links_production_id_idx"     ON "short_links"      ("production_id");
CREATE INDEX IF NOT EXISTS "productions_status_idx"            ON "productions"       ("status");
CREATE INDEX IF NOT EXISTS "productions_created_by_idx"        ON "productions"       ("created_by");
CREATE INDEX IF NOT EXISTS "return_feeds_sort_order_idx"       ON "return_feeds"      ("sort_order");
CREATE INDEX IF NOT EXISTS "whep_servers_is_active_idx"        ON "whep_servers"      ("is_active");
CREATE INDEX IF NOT EXISTS "whep_servers_sort_order_idx"       ON "whep_servers"      ("sort_order");

-- ============================================================
-- DEFAULT RETURN FEEDS SEED
-- Only inserts if the table is empty (first-time setup).
-- ============================================================

INSERT INTO "return_feeds" ("label", "stream_name", "sort_order")
SELECT label, stream_name, sort_order FROM (VALUES
  ('Socal 1', 'Socal1',      1),
  ('Socal 2', 'Socal2',      2),
  ('Socal 3', 'Socal3',      3),
  ('Socal 4', 'Socal4',      4),
  ('Socal 5', 'Socal5',      5),
  ('Socal 6', 'Socal6',      6),
  ('Plex 1',  'livestream',  7),
  ('Plex 2',  'livestream2', 8),
  ('Plex 3',  'livestream3', 9),
  ('Plex 4',  'livestream4', 10),
  ('Plex 5',  'livestream5', 11),
  ('Plex 6',  'livestream6', 12),
  ('Plex 7',  'livestream7', 13),
  ('Plex 8',  'livestream8', 14)
) AS v(label, stream_name, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM "return_feeds" LIMIT 1);

-- ============================================================
-- VERIFICATION
-- ============================================================

SELECT
    '0003 Migration Verification' AS migration,
    CASE
        WHEN (
            SELECT COUNT(*) FROM information_schema.tables
            WHERE table_schema = 'public'
            AND table_name IN ('return_feeds', 'whep_servers', 'productions')
        ) = 3
        THEN 'SUCCESS: return_feeds, whep_servers, productions all present'
        ELSE 'ERROR: One or more new tables missing'
    END AS tables_check,
    CASE
        WHEN (
            SELECT COUNT(*) FROM information_schema.columns
            WHERE table_name IN ('generated_links', 'short_links', 'viewer_links', 'short_viewer_links')
            AND column_name = 'assigned_whep_server'
        ) = 4
        THEN 'SUCCESS: assigned_whep_server on all 4 link tables'
        ELSE 'ERROR: assigned_whep_server missing from one or more link tables'
    END AS column_check;

\echo 'Migration 0003 (return_feeds + whep_servers + assigned_whep_server) completed'
